<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "abexto_xbootstrap_components"
 *
 * Auto generated by Extension Builder 2019-07-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Abexto Extended Bootstrap Components',
    'category' => 'templates',
    'description' => 'Extends the capabilities of bootstrap_package',
    'author' => 'Andreas Prucha',
    'author_email' => 'andreas.prucha@gmail.com',
    'author_company' => 'Abexto - Helicon Software Development',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
            'bootstrap_package' => '10.0.1-10.0.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
